const fs = require('fs')
const path = require('path')
const {
  buildCategoryMap,
  fetchAll,
  getDefaultReportsDir,
  hasArabic,
  hasLatin,
  looksTrulyUnrelated,
  isMolHanoutCompatible,
} = require('./product-review-utils.cjs')

// ─── Dictionnaire français → arabe (épicerie / mol hanout marocain) ───
// Trié du plus long au plus court pour matcher les phrases d'abord
const FR_AR_DICT = [
  // Phrases longues d'abord
  ['lait de coco fluide', 'حليب جوز الهند سائل'],
  ['lait de coco light', 'حليب جوز الهند لايت'],
  ['lait de coco', 'حليب جوز الهند'],
  ['lait en poudre', 'حليب مجفف'],
  ['lait concentré', 'حليب مركز'],
  ['lait entier', 'حليب كامل'],
  ['lait demi-écrémé', 'حليب نصف دسم'],
  ['lait écrémé', 'حليب خالي الدسم'],
  ['lait frais', 'حليب طازج'],
  ['crème fraîche', 'قشدة طازجة'],
  ['crème fraiche', 'قشدة طازجة'],
  ['crème légère', 'قشدة خفيفة'],
  ['crème dessert', 'قشدة حلوى'],
  ['crème caramel', 'قشدة كراميل'],
  ['crème brûlée', 'قشدة محروقة'],
  ['crème chantilly', 'قشدة شانتيي'],
  ['crème oxydante', 'كريم مؤكسد'],
  ['crème hydratante', 'كريم مرطب'],
  ['crème à raser', 'كريم حلاقة'],
  ['crème mains', 'كريم يدين'],
  ['crème de marrons', 'قشدة الكستناء'],
  ['crème pâtissière', 'قشدة حلويات'],
  ['crème fraiche', 'قشدة طازجة'],
  ['fromage blanc', 'جبن أبيض'],
  ['fromage fondu', 'جبن مذاب'],
  ['fromage frais', 'جبن طري'],
  ['fromage râpé', 'جبن مبشور'],
  ['fromage à tartiner', 'جبن للدهن'],
  ['yaourt nature', 'زبادي طبيعي'],
  ['yaourt aux fruits', 'زبادي بالفواكه'],
  ['yaourt à boire', 'زبادي للشرب'],
  ['huile d\'olive', 'زيت زيتون'],
  ['huile de tournesol', 'زيت دوار الشمس'],
  ['huile de soja', 'زيت الصويا'],
  ['huile de colza', 'زيت اللفت'],
  ['huile végétale', 'زيت نباتي'],
  ['vinaigre de cidre', 'خل تفاح'],
  ['vinaigre balsamique', 'خل بلسمي'],
  ['vinaigre de vin', 'خل نبيذ'],
  ['sauce piquante', 'صلصة حارة'],
  ['sauce algérienne', 'صلصة جزائرية'],
  ['sauce chocolat', 'صلصة شوكولاطة'],
  ['confiture de figue', 'مربى تين'],
  ['confiture d\'orange', 'مربى برتقال'],
  ['confiture de fraise', 'مربى فراولة'],
  ['confiture d\'abricot', 'مربى مشمش'],
  ['miel de thym', 'عسل زعتر'],
  ['miel de fleurs', 'عسل زهور'],
  ['eau minérale', 'ماء معدني'],
  ['eau minéral', 'ماء معدني'],
  ['eau de toilette', 'ماء تواليت'],
  ['boisson gazeuse', 'مشروب غازي'],
  ['boisson énergisante', 'مشروب طاقي'],
  ['boisson tropicale', 'مشروب استوائي'],
  ['jus d\'orange', 'عصير برتقال'],
  ['jus de pomme', 'عصير تفاح'],
  ['jus de fruits', 'عصير فواكه'],
  ['jus de mangue', 'عصير مانجو'],
  ['jus de citron', 'عصير ليمون'],
  ['jus de carotte', 'عصير جزر'],
  ['jus multifruits', 'عصير فواكه مشكلة'],
  ['pâte à tartiner', 'عجينة للدهن'],
  ['pâte de fruits', 'عجينة فواكه'],
  ['pâte à crêpes', 'عجينة كريب'],
  ['petit-beurre', 'بيتي بوير'],
  ['petit beurre', 'بيتي بوير'],
  ['papier toilette', 'ورق تواليت'],
  ['liquide vaisselle', 'سائل غسيل الأطباق'],
  ['sac poubelle', 'كيس قمامة'],
  ['gel douche', 'جل استحمام'],
  ['savon noir', 'صابون أسود'],
  ['savon de marseille', 'صابون مرسيليا'],
  ['maïzena fleur', 'مايزينا زهرة'],
  ['fleur de maïs', 'زهرة الذرة'],
  ['maïs doux', 'ذرة حلوة'],
  ['pois chiche', 'حمص'],
  ['petit pois', 'بازلاء'],
  ['pomme de terre', 'بطاطا'],
  ['chocolat en poudre', 'شوكولاطة بودرة'],
  ['cacao en poudre', 'كاكاو بودرة'],
  ['poudre cacaotée', 'بودرة كاكاو'],
  ['café soluble', 'قهوة سريعة التحضير'],
  ['café moulu', 'قهوة مطحونة'],
  ['café en grains', 'قهوة حبوب'],
  ['capsule de café', 'كبسولة قهوة'],
  ['sachet de thé', 'كيس شاي'],
  ['thé à la menthe', 'شاي بالنعناع'],
  ['thé vert', 'شاي أخضر'],
  ['thé noir', 'شاي أسود'],
  ['mousse à raser', 'رغوة حلاقة'],
  ['après-shampooing', 'بلسم شعر'],
  ['brosse à dents', 'فرشاة أسنان'],
  ['coton-tige', 'عصا قطنية'],
  ['couches bébé', 'حفاضات أطفال'],
  ['margrine de table', 'مارغرين طاولة'],
  ['margarine de table', 'مارغرين طاولة'],
  ['beurre pasteurisé', 'زبدة مبسترة'],
  ['beurre allégé', 'زبدة خفيفة'],
  ['beurre jaouda', 'زبدة جودة'],
  ['citron cuisine', 'ليمون طبخ'],
  ['soja cuisine', 'صويا طبخ'],
  ['soja cuisine fluide', 'صويا طبخ سائل'],
  ['huile de table', 'زيت طاولة'],
  ['farine de blé', 'دقيق القمح'],
  ['farine de maïs', 'دقيق الذرة'],
  ['farine de riz', 'دقيق الأرز'],
  ['confit de canard', 'كونفي بطة'],
  ['rôti de boeuf', 'روستو لحم بقر'],
  ['saucisson sec', 'سوسيسون جاف'],
  ['merguez épicé', 'مرقاز حار'],
  ['mortadelle aux fines herbes', 'مرتديلا بالأعشاب'],
  ['mortadelle aux olives', 'مرتديلا بالزيتون'],
  ['mortadelle au poulet', 'مرتديلا بالدجاج'],
  ['mortadelle de boeuf', 'مرتديلا لحم بقر'],
  ['lait de toilette', 'حليب تنظيف'],
  ['sans gluten', 'بدون غلوتين'],
  ['sans sucre', 'بدون سكر'],
  ['sugar free', 'بدون سكر'],
  ['fat free', 'بدون دسم'],
  ['low fat', 'قليل الدسم'],

  // Mots simples
  ['lait', 'حليب'],
  ['beurre', 'زبدة'],
  ['fromage', 'جبن'],
  ['crème', 'قشدة'],
  ['creme', 'قشدة'],
  ['yaourt', 'زبادي'],
  ['café', 'قهوة'],
  ['thé', 'شاي'],
  ['the', 'شاي'],
  ['sucre', 'سكر'],
  ['sel', 'ملح'],
  ['farine', 'دقيق'],
  ['huile', 'زيت'],
  ['riz', 'أرز'],
  ['pâtes', 'معكرونة'],
  ['pates', 'معكرونة'],
  ['pain', 'خبز'],
  ['biscuit', 'بسكويت'],
  ['biscuits', 'بسكويت'],
  ['gaufrette', 'ويفر'],
  ['gaufrettes', 'ويفر'],
  ['chocolat', 'شوكولاطة'],
  ['bonbon', 'حلوى'],
  ['confiture', 'مربى'],
  ['miel', 'عسل'],
  ['sauce', 'صلصة'],
  ['ketchup', 'كاتشب'],
  ['mayonnaise', 'مايونيز'],
  ['moutarde', 'خردل'],
  ['vinaigre', 'خل'],
  ['épices', 'توابل'],
  ['epices', 'توابل'],
  ['poivre', 'فلفل'],
  ['cannelle', 'قرفة'],
  ['curcuma', 'كركم'],
  ['cumin', 'كمون'],
  ['coriandre', 'كزبرة'],
  ['paprika', 'بابريكا'],
  ['gingembre', 'زنجبيل'],
  ['anis', 'يانسون'],
  ['safran', 'زعفران'],
  ['tomate', 'طماطم'],
  ['tomates', 'طماطم'],
  ['thon', 'تونة'],
  ['sardine', 'سردين'],
  ['sardines', 'سردين'],
  ['poisson', 'سمك'],
  ['viande', 'لحم'],
  ['poulet', 'دجاج'],
  ['dinde', 'ديك رومي'],
  ['merguez', 'مرقاز'],
  ['mortadelle', 'مرتديلا'],
  ['saucisse', 'نقانق'],
  ['jambon', 'لحم مدخن'],
  ['œuf', 'بيض'],
  ['oeuf', 'بيض'],
  ['oeufs', 'بيض'],
  ['légume', 'خضر'],
  ['legume', 'خضر'],
  ['légumes', 'خضر'],
  ['legumes', 'خضر'],
  ['fruit', 'فاكهة'],
  ['fruits', 'فواكه'],
  ['olive', 'زيتون'],
  ['olives', 'زيتون'],
  ['haricot', 'فاصوليا'],
  ['haricots', 'فاصوليا'],
  ['lentille', 'عدس'],
  ['lentilles', 'عدس'],
  ['maïs', 'ذرة'],
  ['mais', 'ذرة'],
  ['carotte', 'جزر'],
  ['oignon', 'بصل'],
  ['ail', 'ثوم'],
  ['persil', 'بقدونس'],
  ['menthe', 'نعناع'],
  ['basilic', 'ريحان'],
  ['salade', 'سلطة'],
  ['champignon', 'فطر'],
  ['champignons', 'فطر'],
  ['noix', 'جوز'],
  ['amande', 'لوز'],
  ['amandes', 'لوز'],
  ['noisette', 'بندق'],
  ['noisettes', 'بندق'],
  ['cacahuète', 'فول سوداني'],
  ['cacahuètes', 'فول سوداني'],
  ['cacahuete', 'فول سوداني'],
  ['cacahuetes', 'فول سوداني'],
  ['pistache', 'فستق'],
  ['raisin', 'عنب'],
  ['figue', 'تين'],
  ['datte', 'تمر'],
  ['dattes', 'تمور'],
  ['abricot', 'مشمش'],
  ['orange', 'برتقال'],
  ['citron', 'ليمون'],
  ['pomme', 'تفاح'],
  ['banane', 'موز'],
  ['fraise', 'فراولة'],
  ['fraises', 'فراولة'],
  ['ananas', 'أناناس'],
  ['mangue', 'مانجو'],
  ['pastèque', 'بطيخ'],
  ['melon', 'شمام'],
  ['grenade', 'رمان'],
  ['kiwi', 'كيوي'],
  ['pêche', 'خوخ'],
  ['peche', 'خوخ'],
  ['pruneau', 'برقوق مجفف'],
  ['pruneaux', 'برقوق مجفف'],
  ['jus', 'عصير'],
  ['boisson', 'مشروب'],
  ['boissons', 'مشروبات'],
  ['eau', 'ماء'],
  ['sirop', 'شراب'],
  ['limonade', 'ليموناضة'],
  ['soda', 'صودا'],
  ['bière', 'بيرة'],
  ['chips', 'شيبس'],
  ['croissant', 'كرواسون'],
  ['brioche', 'بريوش'],
  ['madeleine', 'مادلين'],
  ['cookie', 'كوكي'],
  ['cookies', 'كوكي'],
  ['cake', 'كيك'],
  ['gateau', 'كيك'],
  ['gâteau', 'كيك'],
  ['waffle', 'وفل'],
  ['waffles', 'وفل'],
  ['céréales', 'حبوب'],
  ['cereales', 'حبوب'],
  ['muesli', 'موسلي'],
  ['granola', 'غرنولة'],
  ['soupe', 'شوربة'],
  ['bouillon', 'مرق'],
  ['cube', 'مكعب'],
  ['cubes', 'مكعبات'],
  ['nouilles', 'نودلز'],
  ['nouille', 'نودلز'],
  ['ramen', 'رامن'],
  ['couscous', 'كسكس'],
  ['semoule', 'سميد'],
  ['boulgour', 'برغل'],
  ['quinoa', 'كينوا'],
  ['conserves', 'معلبات'],
  ['conserve', 'معلبات'],
  ['cornichon', 'مخلل'],
  ['cornichons', 'مخللات'],
  ['pickles', 'مخللات'],
  ['houmous', 'حمص'],
  ['tahini', 'طحينة'],
  ['tahina', 'طحينة'],
  ['nutella', 'نوتيلا'],
  ['levure', 'خميرة'],
  ['bicarbonate', 'بيكربونات'],
  ['vanille', 'فانيلا'],
  ['cacao', 'كاكاو'],
  ['nature', 'طبيعي'],
  ['bio', 'بيو'],
  ['allégé', 'خفيف'],
  ['allege', 'خفيف'],
  ['light', 'لايت'],
  ['diet', 'دايت'],
  ['zero', 'زيرو'],
  ['frais', 'طازج'],
  ['surgelé', 'مجمد'],
  ['surgele', 'مجمد'],
  ['surgelés', 'مجمدات'],
  ['congelé', 'مجمد'],
  ['savon', 'صابون'],
  ['shampooing', 'شامبو'],
  ['shampoo', 'شامبو'],
  ['dentifrice', 'معجون أسنان'],
  ['déodorant', 'مزيل عرق'],
  ['deodorant', 'مزيل عرق'],
  ['parfum', 'عطر'],
  ['coton', 'قطن'],
  ['mouchoir', 'منديل'],
  ['mouchoirs', 'مناديل'],
  ['lessive', 'مسحوق غسيل'],
  ['détergent', 'منظف'],
  ['detergent', 'منظف'],
  ['nettoyant', 'منظف'],
  ['éponge', 'إسفنجة'],
  ['eponge', 'إسفنجة'],
  ['allumette', 'عود ثقاب'],
  ['allumettes', 'أعواد ثقاب'],
  ['bougie', 'شمعة'],
  ['briquet', 'ولاعة'],
  ['rasoir', 'موس حلاقة'],
  ['couche', 'حفاضة'],
  ['couches', 'حفاضات'],
  ['baume', 'بلسم'],
  ['coloration', 'صبغة'],
  ['teinture', 'صبغة'],
  ['oxydant', 'مؤكسد'],
  ['mascarpone', 'ماسكاربون'],
  ['ricotta', 'ريكوتا'],
  ['mozzarella', 'موتزاريلا'],
  ['emmental', 'إيمانطال'],
  ['gruyère', 'غرويار'],
  ['salami', 'سلامي'],
  ['bacon', 'بيكون'],
  ['pâté', 'باتيه'],
  ['pate', 'باتيه'],
  ['rillettes', 'رييليت'],
  ['foie', 'كبد'],
  ['crêpes', 'كريب'],
  ['crepes', 'كريب'],
  ['tortilla', 'تورتيلا'],
  ['wrap', 'راب'],
  ['pita', 'بيتا'],
  ['samoussa', 'سمبوسة'],
  ['lasagne', 'لازانيا'],
  ['lasagnes', 'لازانيا'],
  ['spaghetti', 'سباغيتي'],
  ['ravioli', 'رافيولي'],
  ['gnocchi', 'نيوكي'],
  ['nougat', 'نوقا'],
  ['halva', 'حلاوة'],
  ['baklava', 'بقلاوة'],
  ['loukoum', 'راحة الحلقوم'],
  ['sahlep', 'سحلب'],
  ['salep', 'سحلب'],
  ['matcha', 'ماتشا'],
  ['chai', 'تشاي'],
  ['masala', 'مسالا'],
  ['atay', 'أتاي'],
  ['atai', 'أتاي'],
  ['infusion', 'منقوع'],
  ['tisane', 'تيسان'],
  ['camomille', 'بابونج'],
  ['verveine', 'فربين'],
  ['rooibos', 'رويبوس'],
  ['nectar', 'نكتار'],
  ['tablette', 'لوح'],
  ['barre', 'بار'],
  ['barres', 'بارات'],
  ['sachet', 'كيس'],
  ['boite', 'علبة'],
  ['bouteille', 'قارورة'],
  ['flacon', 'قارورة'],
  ['pot', 'وعاء'],
  ['tube', 'أنبوب'],
  ['paquet', 'رزمة'],
  ['brique', 'طوبة'],

  // Unités
  ['litre', 'لتر'],
  ['litres', 'لتر'],
  ['gramme', 'غرام'],
  ['grammes', 'غرام'],
  ['kilo', 'كيلو'],
  ['kilos', 'كيلو'],
  ['ml', 'مل'],
  ['cl', 'سل'],
  ['gr', 'غ'],
  ['kg', 'كغ'],
  ['mg', 'ملغ'],
  ['g', 'غ'],
  ['l', 'لتر'],
  ['1l', '1لتر'],
  ['2l', '2لتر'],
  ['5l', '5لتر'],

  // Marques marocaines courantes (garder en latin, ajouter translittération)
  ['jaouda', 'جودة'],
  ['jaouda', 'جودة'],
  ['sidi ali', 'سيدي علي'],
  ['ain saiss', 'عين سايس'],
  ['ain atlas', 'عين أطلس'],
  ['ain ifrane', 'عين إفران'],
  ['sahara', 'الصحراء'],
  ['doukkala', 'دكالة'],
  ['chergui', 'الشركي'],
  ['le berger', 'الراعي'],
  ['copag', 'كوباج'],
  ['almaghrib', 'المغرب'],
  ['lesieur', 'ليسيو'],
  ['savola', 'سافولا'],
  ['zine', 'زين'],
  ['mabrouka', 'مبروكة'],
  ['afriquia', 'أفريقيا'],
  ['total', 'طوطال'],
  ['shell', 'شيل'],
  ['bonn', 'بون'],
  ['kite', 'كايت'],
  ['hala', 'هالة'],
  ['al wadi', 'الوادي'],
  ['bimo', 'بيمو'],
  ['bimo', 'بيمو'],
  ['aïcha', 'عائشة'],
  ['aicha', 'عائشة'],
  ['moulin d\'or', 'طاحونة الذهب'],
  ['moulin dor', 'طاحونة الذهب'],
  ['dari', 'داري'],
  ['kaby', 'كابي'],
  ['panzani', 'بانزاني'],
  ['barilla', 'باريلا'],
  ['panzani', 'بانزاني'],
  ['candia', 'كانديا'],
  ['danone', 'دانون'],
  ['nestlé', 'نستله'],
  ['nestle', 'نستله'],
  ['yoplait', 'يوبلاي'],
  ['bel', 'بل'],
  ['la vache qui rit', 'البقرة الضاحكة'],
  ['vache qui rit', 'البقرة الضاحكة'],
  ['président', 'بريزيدان'],
  ['president', 'بريزيدان'],
  ['capri-sonne', 'كابري سون'],
  ['capri sonne', 'كابري سون'],
  ['cappy', 'كابي'],
  ['fanta', 'فانتا'],
  ['coca-cola', 'كوكاكولا'],
  ['coca cola', 'كوكاكولا'],
  ['pepsi', 'بيبسي'],
  ['sprite', 'سبرايت'],
  ['mirinda', 'ميرندا'],
  ['seven up', 'سيفن أب'],
  ['7up', 'سيفن أب'],
  ['red bull', 'ريد بول'],
  ['monster', 'مونستر'],
  ['burn', 'بيرن'],
  ['aquafina', 'أكوافينا'],
  ['evian', 'إيفيان'],
  ['volvic', 'فولفيك'],
  ['perrier', 'بيرييه'],
  ['bahlsen', 'بالسن'],
  ['oreo', 'أوريو'],
  ['mikado', 'ميكادو'],
  ['kitkat', 'كيتكات'],
  ['twix', 'توكس'],
  ['mars', 'مارس'],
  ['snickers', 'سنيكرز'],
  ['bounty', 'باونتي'],
  ['m&m', 'إم آند إم'],
  ['ferrero', 'فيرو'],
  ['kinder', 'كيندر'],
  ['milka', 'ميلكا'],
  ['lindt', 'ليندت'],
  ['poulain', 'بولان'],
  ['suchard', 'سوشار'],
  ['nesquik', 'نسكويك'],
  ['maggi', 'ماغي'],
  ['knorr', 'كنور'],
  ['liebig', 'ليبيغ'],
  ['heinz', 'هاينز'],
  ['calvé', 'كالفي'],
  ['calve', 'كالفي'],
  ['bénédicta', 'بنيديكتا'],
  ['benedicta', 'بنيديكتا'],
  ['maille', 'ماي'],
  ['amora', 'أمورا'],
  ['lesieur', 'ليسيو'],
  ['fleur d\'or', 'زهرة الذهب'],
  ['fleur dor', 'زهرة الذهب'],
  ['médina', 'المدينة'],
  ['medina', 'المدينة'],
  ['épi d\'or', 'سنبلة الذهب'],
  ['epi dor', 'سنبلة الذهب'],
  ['al baraka', 'البركة'],
  ['baraka', 'البركة'],
  ['adghal', 'أدغال'],
  ['ifri', 'إيفري'],
  ['sidi harazem', 'سيدي حرازم'],
  ['mgharba', 'مغاربة'],
  ['haj lahlou', 'الحاج لعللو'],
  ['dolce gusto', 'دولشي غوستو'],
  ['nespresso', 'نسبريسو'],
  ['tassimo', 'تاسيمو'],
  ['jardin bio', 'جاردن بيو'],
  ['bjorg', 'بيورغ'],
  ['marjane', 'مرجان'],
  ['atlas', 'أطلس'],
  ['refiane', 'رفيان'],
  ['refiane', 'رفيان'],
  ['khadija', 'خديجة'],
  ['rahma', 'رحمة'],
  ['nina', 'نينا'],
  ['moulinex', 'مولينكس'],
  ['tefal', 'تفال'],
  ['seb', 'سب'],
  ['krups', 'كروبس'],
  ['braun', 'براون'],
  ['philips', 'فيليبس'],
  ['balea', 'باليا'],
  ['dm', 'دي إم'],
  ['rossmann', 'روسمان'],
  ['dove', 'دوف'],
  ['nivea', 'نيفيا'],
  ['rexona', 'ريكسونا'],
  ['axe', 'اكس'],
  ['brut', 'بروت'],
  ['garnier', 'غارنييه'],
  ['loreal', 'لوريال'],
  ['l\'oréal', 'لوريال'],
  ['schwarzkopf', 'شفارتسكوف'],
  ['head shoulders', 'هيد آند شولدرز'],
  ['pantene', 'بانتين'],
  ['tresemmé', 'تريزيميه'],
  ['fructis', 'فروكتيس'],
  ['elseve', 'إلسيف'],
  ['crystal', 'كريستال'],
  ['palmolive', 'بالموليف'],
  ['colgate', 'كولغيت'],
  ['signal', 'سيغنال'],
  ['oral-b', 'أورال بي'],
  ['gillette', 'جيليت'],
  ['wilkinson', 'ويلكنسون'],
  ['bic', 'بيك'],
  ['always', 'ألوايز'],
  ['nana', 'نانا'],
  ['kotex', 'كوتكس'],
  ['pampers', 'بامبرز'],
  ['huggies', 'هاغيز'],
  ['persil', 'بيرسيل'],
  ['skip', 'سكيب'],
  ['ariel', 'أريال'],
  ['tide', 'تايد'],
  ['omo', 'أومو'],
  ['harpic', 'هاربيك'],
  ['mr propre', 'مسيو بروبر'],
  ['ajax', 'أجاكس'],
  [' domestos', 'دوميستوس'],
  ['carrefour', 'كارفور'],
  ['auchan', 'أوشان'],
  ['leader price', 'ليدر برايس'],
  ['u', 'يو'],
  ['casino', 'كازينو'],
  ['cora', 'كورا'],
  ['monoprix', 'مونوبري'],
  ['intermarché', 'انترمارسية'],
  ['leclerc', 'لوكليرك'],
  ['déliplus', 'ديليبلوس'],
  ['deliplus', 'ديليبلوس'],
  ['compy', 'كومبي'],
  ['hacendado', 'هاسيندادو'],
  ['bosque verde', 'بوسكي فيريدي'],
  ['consum', 'كونسوم'],
  ['eroski', 'يروسكي'],
  ['mercadona', 'ميركادونا'],

  // Connecteurs & prépositions
  ['de', ''],
  ["d'", ''],
  ['aux', 'بـ'],
  ["aux fines herbes", 'بالأعشاب'],
  ["aux olives", 'بالزيتون'],
  ['au', 'بـ'],
  ["au poulet", 'بالدجاج'],
  ["au chocolat", 'بالشوكولاطة'],
  ["à la", 'بـ'],
  ["à", 'بـ'],
  ['et', 'و'],
  ['en', ''],
  ['du', ''],
  ['des', ''],
  ['le', ''],
  ['la', ''],
  ['les', ''],
  ['un', ''],
  ['une', ''],
  ['pour', 'لـ'],
  ['avec', 'مع'],
  ['sans', 'بدون'],
  ['sur', 'على'],

  // Fruits supplémentaires
  ['framboises', 'الفراولة'],
  ['framboise', 'الفراولة'],
  ['myrtilles', 'التوت البري'],
  ['myrtille', 'التوت البري'],
  ['prunes', 'البرقوق'],
  ['prune', 'البرقوق'],
  ['abricots', 'المشمش'],
  ['abricot', 'المشمش'],
  ['oranges', 'البرتقال'],
  ['citrons', 'الليمون'],
  ['figues', 'التين'],
  ['pêches', 'الخوخ'],
  ['pommes', 'التفاح'],
  ['bananes', 'الموز'],
  ['fraises', 'الفراولة'],
  ['raisins', 'العنب'],
  ['mandarines', 'الماندارين'],
  ['clémentines', 'القلامنتين'],
  ['clementines', 'القلامنتين'],

  // Descripteurs courants
  ['naturel', 'طبيعي'],
  ['naturelle', 'طبيعية'],
  ['entier', 'كامل'],
  ['entière', 'كاملة'],
  ['entiere', 'كاملة'],
  ['demi-écrémé', 'نصف دسم'],
  ['demi-écrémée', 'نصف دسم'],
  ['demi ecréme', 'نصف دسم'],
  ['écrémé', 'خالي الدسم'],
  ['écrémée', 'خالية الدسم'],
  ['ecreme', 'خالي الدسم'],
  ['allégé', 'خفيف'],
  ['allégée', 'خفيفة'],
  ['fort', 'قوي'],
  ['forte', 'قوية'],
  ['doux', 'حلو'],
  ['douce', 'حلوة'],
  ['pur', 'نقي'],
  ['pure', 'نقية'],
  ['fin', 'رفيع'],
  ['fine', 'رفيعة'],
  ['extra', 'إكسترا'],
  ['supérieur', 'ممتاز'],
  ['supérieure', 'ممتازة'],
  ['premium', 'بريميوم'],
  ['classique', 'كلاسيك'],
  ['original', 'أوريجينال'],
  ['classique', 'كلاسيك'],
  ['spécial', 'خاص'],
  ['spéciale', 'خاصة'],
  ['grand', 'كبير'],
  ['grande', 'كبيرة'],
  ['petit', 'صغير'],
  ['petite', 'صغيرة'],
  ['mini', 'ميني'],
  ['maxi', 'ماكسي'],
  ['familial', 'عائلي'],
  ['familiale', 'عائلية'],
  ['économique', 'اقتصادي'],
  ['economique', 'اقتصادي'],
  ['épais', 'سميك'],
  ['épaisse', 'سميكة'],
  ['moulu', 'مطحون'],
  ['moulue', 'مطحونة'],
  ['concassé', 'مهروش'],
  ['concassée', 'مهروشة'],
  ['émincé', 'مقطع'],
  ['émincée', 'مقطعة'],
  ['râpé', 'مبشور'],
  ['râpée', 'مبشورة'],
  ['rape', 'مبشور'],
  ['tranché', 'مشرّح'],
  ['tranchée', 'مشرّحة'],
  ['en tranches', 'شرائح'],
  ['en poudre', 'بودرة'],
  ['en grains', 'حبوب'],
  ['en sachets', 'أكياس'],
  ['en bouteille', 'قارورة'],
  ['en boite', 'علبة'],
  ['liquide', 'سائل'],
  ['solide', 'صلب'],
  ['concentré', 'مركز'],
  ['concentrée', 'مركزة'],
  ['concentre', 'مركز'],
  ['dilué', 'مخفف'],
  ['instantané', 'سريع'],
  ['instantanée', 'سريعة'],
  ['instant', 'سريع'],
  ['rapide', 'سريع'],
  ['séché', 'مجفف'],
  ['séchée', 'مجففة'],
  ['seche', 'مجفف'],
  ['fumé', 'مدخن'],
  ['fumée', 'مدخنة'],
  ['fume', 'مدخن'],
  ['fermenté', 'مخمر'],
  ['cuit', 'مطبوخ'],
  ['cuite', 'مطبوخة'],
  ['cru', 'نيء'],
  ['crue', 'نيئة'],
  ['frit', 'مقلي'],
  ['frite', 'مقلية'],
  ['grillé', 'محمص'],
  ['grillée', 'محمصة'],
  ['grille', 'محمص'],
  ['roti', 'مشوي'],
  ['rôti', 'مشوي'],
  ['rotie', 'مشوية'],
  ['rôtie', 'مشوية'],
  ['bouilli', 'مسلوق'],
  ['bouillie', 'مسلوقة'],
  ['vapeur', 'بخار'],
  ['poêlé', 'مقلاة'],
  ['revenu', 'مرجوع'],

  // Types de préparation / plats
  ['prêt à consommer', 'جاهز للأكل'],
  ['prêt à l\'emploi', 'جاهز للاستعمال'],
  ['à cuire', 'للطبخ'],
  ['à tartiner', 'للدهن'],
  ['à boire', 'للشرب'],
  ['de table', 'طاولة'],
  ['de cuisine', 'طبخ'],
  ['pour cuisiner', 'للطبخ'],

  // Autres produits courants
  ['corn flakes', 'رقاق الذرة'],
  ['cornflakes', 'رقاق الذرة'],
  ['chocos', 'شوكوس'],
  ['coco pops', 'كوكو بوبس'],
  ['nesquik', 'نسكويك'],
  ['trident', 'ترايدنت'],
  ['stimorol', 'ستيمورول'],
  ['extra', 'إكسترا'],
  ['halls', 'هولز'],
  ['vicks', 'فيكس'],
  ['chiclets', 'شيكليت'],
  ['malabar', 'مالابار'],
  ['turbo', 'توربو'],

  // Épicerie marocaine
  ['ras el hanout', 'رأس الحانوت'],
  ['chermoula', 'شرمولة'],
  ['harissa', 'هريسة'],
  ['harira', 'حريرة'],
  ['rfissa', 'رفيسة'],
  ['seffa', 'سفة'],
  ['briouats', 'بريوات'],
  ['pastilla', 'بسطيلة'],
  ['baghrir', 'بغرير'],
  ['msemen', 'مسمن'],
  ['harcha', 'حرشة'],
  ['meloui', 'ملوي'],
  ['meloui', 'ملوي'],
  ['grillades', 'مشويات'],
  ['kefta', 'كفتة'],
  ['kaab ghzal', 'كعب الغزال'],
  ['ghribia', 'غريبة'],
  ['chbakia', 'الشباكية'],
  ['briouat', 'بريوات'],
  ['makrout', 'مقروض'],
  ['zellige', 'زليج'],
  ['sellou', 'السلو'],
  ['amlou', 'أملو'],
  ['smen', 'سمن'],
  ['jben', 'جبن'],
  ['raib', 'ريب'],
  ['leben', 'لبن'],
  ['lben', 'لبن'],
  ['beldi', 'بلدي'],
  ['chih', 'الشيح'],
  ['z\'itra', 'الزعتر'],
  ['zitrouna', 'الزيترونة'],
  ['louiza', 'اللويزة'],
  ['flio', 'فليو'],
  ['marjane', 'مرجان'],
]

function translateName(name) {
  if (!name || hasArabic(name) && !hasLatin(name)) return name

  let result = name

  // Appliquer les traductions du plus long au plus court
  // Utiliser des limites de mot adaptées (évite de corrompre "Poulain" en remplaçant "l")
  for (const [fr, ar] of FR_AR_DICT) {
    const escaped = fr.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    const regex = new RegExp(`(?<=^|[\\s\\-.,;:!?/()"'"])${escaped}(?=[\\s\\-.,;:!?/()"'"]|$)`, 'gi')
    result = result.replace(regex, ar)
  }

  // Nettoyage post-traduction
  // 1. "d'" ou "D'" collé à un mot arabe → supprimer (ex: "d'المشمش" → "المشمش")
  result = result.replace(/[dD]'\s*(?=[\u0600-\u06FF])/g, '')
  // 2. "بـ" collé au mot suivant → ajouter espace (ex: "بـحليب" → "بـ حليب")
  result = result.replace(/بـ(?=[\u0600-\u06FF])/g, 'بـ ')
  // 3. Espaces multiples → un seul
  result = result.replace(/\s{2,}/g, ' ')
  // 4. Espace avant tiret déjà présent
  result = result.replace(/\s+-\s+/g, ' - ')
  // 5. Espace isolé au début/fin
  result = result.replace(/^\s+|\s+$/gm, '')
  // 6. Double tiret
  result = result.replace(/-\s*-/g, '-')
  // 7. "بـ " avant un mot latin (inutile) → supprimer
  result = result.replace(/بـ\s+(?=[A-Za-z])/g, '')
  // 8. Espace avant apostrophe
  result = result.replace(/\s+'/g, "'")

  return result.trim()
}

async function main() {
  const reportsDir = getDefaultReportsDir()
  fs.mkdirSync(reportsDir, { recursive: true })

  console.log('📦 Chargement des produits Supabase...')
  const [products, categories] = await Promise.all([
    fetchAll('products', 'id,name_ar,sku,category_id,is_active', 'name_ar.asc'),
    fetchAll('product_categories', 'id,name_ar,name_en', 'name_ar.asc'),
  ])
  const categoryMap = buildCategoryMap(categories)

  const translations = []
  let translatedCount = 0
  let unchangedCount = 0
  let alreadyArabicCount = 0

  for (const product of products) {
    const currentName = String(product.name_ar || '').trim()
    const categoryName = categoryMap.get(product.category_id) || ''

    // Skip inactive
    if (product.is_active === false) continue

    // Skip already fully Arabic
    if (hasArabic(currentName) && !hasLatin(currentName)) {
      alreadyArabicCount++
      continue
    }

    // Skip truly unrelated
    if (looksTrulyUnrelated(currentName, categoryName)) continue

    const newName = translateName(currentName)

    if (newName !== currentName && newName.trim()) {
      translations.push({
        id: product.id,
        sku: product.sku,
        current_name_ar: currentName,
        new_name_ar: newName,
        category_name: categoryName,
      })
      translatedCount++
    } else {
      unchangedCount++
    }
  }

  // Save
  fs.writeFileSync(
    path.join(reportsDir, 'product-translations.json'),
    JSON.stringify(translations, null, 2)
  )

  const summary = {
    total_active: products.filter(p => p.is_active !== false).length,
    already_arabic: alreadyArabicCount,
    translated: translatedCount,
    unchanged: unchangedCount,
  }
  fs.writeFileSync(
    path.join(reportsDir, 'product-translations-summary.json'),
    JSON.stringify(summary, null, 2)
  )

  console.log('\n✅ Traductions générées:')
  console.log(JSON.stringify(summary, null, 2))
  console.log(`\n📁 Fichier: reports/product-translations.json`)
  console.log('\nÉchantillon (20):')
  console.log(JSON.stringify(translations.slice(0, 20).map(t => ({
    current: t.current_name_ar,
    new: t.new_name_ar,
  })), null, 2))
}

main().catch(e => { console.error(e); process.exit(1) })
